# Generated by Django 4.2.7 on 2023-12-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatLogs',
            new_name='ChatLog',
        ),
    ]
