# Generated by Django 4.2.7 on 2023-12-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_chatlogs_chatlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='chat_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='prompt',
            field=models.TextField(null=True),
        ),
    ]
