# Generated by Django 4.2.7 on 2023-12-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatlog_chat_title_alter_chatlog_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='header',
            field=models.SmallIntegerField(choices=[(1, 'Header'), (0, 'Content')], default=0),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'none'), (1, 'User'), (2, 'ChatGPT')], default=0),
        ),
    ]
