# Generated by Django 4.2.7 on 2023-12-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatlog_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'User'), (2, 'ChatGPT')], default=0),
        ),
    ]
